<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EscortSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //Data to store
        $data = [
            [

                'user_id' => 5,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                "escort_name"=>"Ta Baiseuse de luxe",
                'ethnic_id'=>2,
                'shape_id'=>1,
                'whatsapp_number'=>'693103785',
                'age'=>'20',
                'sexuality'=>'Heterosexuelle',
                'description'=>'Je suis une jolie fille noire vivant a Douala disponible pour vous satisafaire',
                'isVerified'=>0,
                'isCompleted'=>1,
                'quarter_id' => 1,
                'photo'=> '1-1523698.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 6,
                "skin_color_id"=>2,
                "escort_name"=>"lèche Vagin automatique",
                "height_id"=>1,
                "weight_id"=>2,
                'ethnic_id'=>2,
                'shape_id'=>2,
                'whatsapp_number'=>'698034224',
                'age'=>'28',
                'sexuality'=>'Bisexuelle',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 1,
                'isCompleted'=>1,
                'photo'=> '2-142536.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 7,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                "escort_name"=>"Pipe woman",
                'ethnic_id'=>2,
                'shape_id'=>3,
                'whatsapp_number'=>'697434224',
                'age'=>'19',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 1,
                'isCompleted'=>1,
                'photo'=> '3-141411.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 8,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                "escort_name"=>"mignon cul",
                'ethnic_id'=>2,
                'shape_id'=>1,
                'whatsapp_number'=>'697256314',
                'age'=>'20',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 6,
                'isCompleted'=>1,
                'photo'=> '4-101011.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 9,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                "escort_name"=>"Ta Saloppe de luxe",
                'ethnic_id'=>2,
                'shape_id'=>1,
                'whatsapp_number'=>'657434226',
                'age'=>'17',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 6,
                'isCompleted'=>1,
                'photo'=> '5-555550.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 10,
                'ethnic_id'=>2,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                'shape_id'=>1,
                "escort_name"=>"Chaton sawa",
                'whatsapp_number'=>'677434224',
                'age'=>'26',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 8,
                'isCompleted'=>1,
                'photo'=> '6-666662.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 11,
                'ethnic_id'=>2,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                'shape_id'=>1,
                "escort_name"=>"Le Feu de bangala",
                'whatsapp_number'=>'678251224',
                'age'=>'20',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 8,
                'isCompleted'=>1,
                'photo'=> '7-777774.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 12,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                "escort_name"=>"Mignone Chatte",
                'ethnic_id'=>2,
                'shape_id'=>1,
                'whatsapp_number'=>'651253696',
                'age'=>'19',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 22,
                'isCompleted'=>1,
                'photo'=> '8-888880.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 13,
                "skin_color_id"=>1,
                'ethnic_id'=>2,
                "height_id"=>1,
                "weight_id"=>2,
                'shape_id'=>1,
                'isCompleted'=>1,
                "escort_name"=>"Bangala Domain",
                'whatsapp_number'=>'658789652',
                'age'=>'25',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 32,
                'photo'=> '9-999993.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 14,
                "skin_color_id"=>1,
                'ethnic_id'=>2,
                "height_id"=>1,
                "weight_id"=>2,
                'shape_id'=>3,
                'isCompleted'=>1,
                "escort_name"=>"Ta Baiseuse Bami",
                'whatsapp_number'=>'696365241',
                'age'=>'12',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 32,
                'photo'=> '10-101010.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 15,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                'ethnic_id'=>2,
                'shape_id'=>2,
                'whatsapp_number'=>'657968521',
                "escort_name"=>"mangeuse de piment",
                'age'=>'23',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 39,
                'isCompleted'=>1,
                'photo'=> '11-111110.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 16,
                "skin_color_id"=>1,
                'ethnic_id'=>2,
                "height_id"=>1,
                "weight_id"=>2,
                'shape_id'=>1,
                "escort_name"=>"Ta Baiseuse de pimenterie",
                'whatsapp_number'=>'6999856321',
                'age'=>'20',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 39,
                'isCompleted'=>1,
                'photo'=> '12-121213.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 17,
                'ethnic_id'=>2,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                'shape_id'=>1,
                'whatsapp_number'=>'675698541',
                "escort_name"=>"piment de luxe",
                'age'=>'18',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 41,
                'isCompleted'=>1,
                'photo'=> '13-131313.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 18,
                'ethnic_id'=>1,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                'shape_id'=>1,
                "escort_name"=>"Ta Sauvage Beti",
                'whatsapp_number'=>'655415287',
                'age'=>'25',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 46,
                'isCompleted'=>1,
                'photo'=> '14-141410.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 19,
                'ethnic_id'=>5,
                "skin_color_id"=>2,
                "height_id"=>1,
                "weight_id"=>2,
                'shape_id'=>1,
                "escort_name"=>"Cul amer et Sucré",
                'whatsapp_number'=>'658967412',
                'age'=>'28',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 92,
                'isCompleted'=>1,
                'photo'=> '15-151518.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 20,
                'ethnic_id'=>4,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                'shape_id'=>1,
                "escort_name"=>"Tailleuse de Pipe",
                'whatsapp_number'=>'652526396',
                'age'=>'22',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 92,
                'isCompleted'=>1,
                'photo'=> '16-161610.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 21,
                'ethnic_id'=>3,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                'shape_id'=>1,
                "escort_name"=>"Pipe fraiche",
                'whatsapp_number'=>'659859632',
                'age'=>'21',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 93,
                'isCompleted'=>1,
                'photo'=> '17-171711.jpg',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],

        ];
        //Storing Data
        DB::table('escorts')->insert($data);
    }
}
