<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EscortSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //Data to store
        $data = [
            [

                'user_id' => 5,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                "escort_name"=>"Ta Baiseuse de luxe",
                'ethnic_id'=>2,
                'shape_id'=>1,
                'whatsapp_number'=>'693103785',
                'age'=>'20',
                'sexuality'=>'Heterosexuelle',
                'description'=>'Je suis une jolie fille noire vivant a Douala disponible pour vous satisafaire',
                'isVerified'=>0,
                'isCompleted'=>1,
                'quarter_id' => 1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=15&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 6,
                "skin_color_id"=>2,
                "escort_name"=>"lèche Vagin automatique",
                "height_id"=>1,
                "weight_id"=>2,
                'ethnic_id'=>2,
                'shape_id'=>2,
                'whatsapp_number'=>'698034224',
                'age'=>'28',
                'sexuality'=>'Bisexuelle',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 1,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=11&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 7,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                "escort_name"=>"Pipe woman",
                'ethnic_id'=>2,
                'shape_id'=>3,
                'whatsapp_number'=>'697434224',
                'age'=>'19',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 1,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=18&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 8,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                "escort_name"=>"mignon cul",
                'ethnic_id'=>2,
                'shape_id'=>1,
                'whatsapp_number'=>'697256314',
                'age'=>'20',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 1,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=1&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 9,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                "escort_name"=>"Ta Saloppe de luxe",
                'ethnic_id'=>2,
                'shape_id'=>1,
                'whatsapp_number'=>'657434226',
                'age'=>'17',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 6,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=9&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 10,
                'ethnic_id'=>2,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                'shape_id'=>1,
                "escort_name"=>"Chaton sawa",
                'whatsapp_number'=>'677434224',
                'age'=>'26',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 6,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=19&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 11,
                'ethnic_id'=>2,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                'shape_id'=>1,
                "escort_name"=>"Le Feu de bangala",
                'whatsapp_number'=>'678251224',
                'age'=>'20',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 6,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=2&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 12,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                "escort_name"=>"Mignone Chatte",
                'ethnic_id'=>2,
                'shape_id'=>1,
                'whatsapp_number'=>'651253696',
                'age'=>'19',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 7,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=10&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 13,
                "skin_color_id"=>1,
                'ethnic_id'=>2,
                "height_id"=>1,
                "weight_id"=>2,
                'shape_id'=>1,
                'isCompleted'=>1,
                "escort_name"=>"Bangala Domain",
                'whatsapp_number'=>'658789652',
                'age'=>'25',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 7,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=7&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 14,
                "skin_color_id"=>1,
                'ethnic_id'=>2,
                "height_id"=>1,
                "weight_id"=>2,
                'shape_id'=>3,
                'isCompleted'=>1,
                "escort_name"=>"Ta Baiseuse Bami",
                'whatsapp_number'=>'696365241',
                'age'=>'12',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 7,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=4&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 15,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                'ethnic_id'=>2,
                'shape_id'=>2,
                'whatsapp_number'=>'657968521',
                "escort_name"=>"mangeuse de piment",
                'age'=>'23',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 8,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=8&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 16,
                "skin_color_id"=>1,
                'ethnic_id'=>2,
                "height_id"=>1,
                "weight_id"=>2,
                'shape_id'=>1,
                "escort_name"=>"Ta Baiseuse de pimenterie",
                'whatsapp_number'=>'6999856321',
                'age'=>'20',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 8,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=5&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 17,
                'ethnic_id'=>2,
                "skin_color_id"=>1,
                "height_id"=>1,
                "weight_id"=>2,
                'shape_id'=>1,
                'whatsapp_number'=>'675698541',
                "escort_name"=>"piment de luxe",
                'age'=>'18',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 8,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=17&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 18,
                'ethnic_id'=>1,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                'shape_id'=>1,
                "escort_name"=>"Ta Sauvage Beti",
                'whatsapp_number'=>'655415287',
                'age'=>'25',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 8,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=14&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 19,
                'ethnic_id'=>5,
                "skin_color_id"=>2,
                "height_id"=>1,
                "weight_id"=>2,
                'shape_id'=>1,
                "escort_name"=>"Cul amer et Sucré",
                'whatsapp_number'=>'658967412',
                'age'=>'28',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 22,
                'isCompleted'=>1,
                'photo'=> 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRprjwQEoJL6htgncl7KuxQzZTFhb_gYuOU4yLtKMnJgcGVuffsg0cLPYzFT4rib0n8f9A&usqp=CAU',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 20,
                'ethnic_id'=>4,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                'shape_id'=>1,
                "escort_name"=>"Tailleuse de Pipe",
                'whatsapp_number'=>'652526396',
                'age'=>'22',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 32,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=7&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'user_id' => 21,
                'ethnic_id'=>3,
                "height_id"=>1,
                "weight_id"=>2,
                "skin_color_id"=>1,
                'shape_id'=>1,
                "escort_name"=>"Pipe fraiche",
                'whatsapp_number'=>'659859632',
                'age'=>'21',
                'sexuality'=>'Lesbienne',
                'description'=>'Je suis une jolie fille brune vivant a Yaounde disponible pour vous satisafaire',
                'isVerified'=>0,
                'quarter_id' => 32,
                'isCompleted'=>1,
                'photo'=> 'https://premiummod.com/demoimages/img.php?imgid=8&t=es',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],

        ];
        //Storing Data
        DB::table('escorts')->insert($data);
    }
}
